---
- name: Amazon CloudWatch Agent | Include OS-specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "empty.yml"
  tags: amz_cwagent

- name: Amazon CloudWatch Agent | Set dependencies
  set_fact:
    amz_cwagent_dependencies: "{{ __amz_cwagent_dependencies }}"
  when: amz_cwagent_dependencies is not defined
  tags: amz_cwagent

- name: Amazon CloudWatch Agent | Set signature URL
  set_fact:
    amz_cwagent_sig_url: "{{ __amz_cwagent_sig_url }}"
  when: amz_cwagent_sig_url is not defined
  tags: amz_cwagent

- name: Amazon CloudWatch Agent | Set package URL
  set_fact:
    amz_cwagent_pkg_url: "{{ __amz_cwagent_pkg_url }}"
  when: amz_cwagent_pkg_url is not defined
  tags: amz_cwagent

- name: Amazon CloudWatch Agent | Ensure dependencies are installed
  package:
    name: "{{ amz_cwagent_dependencies }}"
    state: latest
  tags: amz_cwagent

- command: echo ~
  register: home_dir
  tags: amz_cwagent

- set_fact: amz_cwagent_pubkey_path="{{ home_dir.stdout }}/{{ amz_cwagent_pubkey_url | basename }}"
  tags: amz_cwagent

- set_fact: amz_cwagent_sig_path="{{ home_dir.stdout }}/{{ amz_cwagent_sig_url | basename }}"
  tags: amz_cwagent

- set_fact: amz_cwagent_pkg_path="{{ home_dir.stdout }}/{{ amz_cwagent_pkg_url | basename }}"
  tags: amz_cwagent

- block:
    - name: Amazon CloudWatch Agent | Download GPG pubkey
      get_url:
        url: "{{ amz_cwagent_pubkey_url }}"
        dest: "{{ amz_cwagent_pubkey_path }}"
        force: yes

    - name: Amazon CloudWatch Agent | Download signature file
      get_url:
        url: "{{ amz_cwagent_sig_url }}"
        dest: "{{ amz_cwagent_sig_path }}"
        force: yes

    - name: Amazon CloudWatch Agent | Download package file
      get_url:
        url: "{{ amz_cwagent_pkg_url }}"
        dest: "{{ amz_cwagent_pkg_path }}"
        force: yes

    - name: Amazon CloudWatch Agent | Import GPG pubkey
      command: >
        gpg --no-greeting --no-auto-check-trustdb -q --batch --no-tty --import {{ amz_cwagent_pubkey_path }}
      register: amz_cwagent_pubkey_import_check
      changed_when: no
      failed_when: amz_cwagent_pubkey_import_check.rc != 0

    - name: Amazon CloudWatch Agent | Verify GPG pubkey
      shell: >
        gpg --with-colons --fingerprint "Amazon CloudWatch Agent" | awk -F":" '$1 == "fpr" {print $10;}'
      args:
        executable: /bin/bash
      register: amz_cwagent_pubkey_fingerprint_reported
      changed_when: no
      failed_when: amz_cwagent_pubkey_fingerprint_reported.stdout != amz_cwagent_pubkey_fingerprint

    - name: Amazon CloudWatch Agent | Verify package file
      command: >
        gpg --no-greeting --no-auto-check-trustdb -q --batch --no-tty --verify {{ amz_cwagent_sig_path }} {{ amz_cwagent_pkg_path }}
      register: amz_cwagent_pkg_check
      changed_when: no
      failed_when: amz_cwagent_pkg_check.rc != 0

    - name: Amazon CloudWatch Agent | Install package
      include_tasks: "{{ ansible_distribution }}.yml"

    - name: Amazon CloudWatch Agent | Ensure run_as user group exists
      group: name={{ amz_cwagent_run_as_group }} state=present

    - name: Amazon CloudWatch Agent | Ensure run_as user exists
      user:
        name: "{{ amz_cwagent_run_as_user }}"
        shell: /bin/true
        group: "{{ amz_cwagent_run_as_group }}"
        home: "{{ amz_cwagent_install_path }}"
        createhome: no
        state: present

    - name: Amazon CloudWatch Agent | Write base config file
      template:
        src: amazon-cloudwatch-agent.json.j2
        dest: "{{ amz_cwagent_conf_path }}/amazon-cloudwatch-agent.json"
        owner: "{{ amz_cwagent_run_as_user }}"
        group: "{{ amz_cwagent_run_as_group }}"

    - name: Amazon CloudWatch Agent | Activate base config
      shell: "{{ amz_cwagent_ctl_bin }} -a {{ amz_cwagent_action }}-config -m {{ amz_cwagent_mode }} -c file:{{ amz_cwagent_conf_path }}/amazon-cloudwatch-agent.json -s"
      args:
        executable: /bin/bash

  always:
    - name: Amazon CloudWatch Agent | Cleanup downloaded files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ amz_cwagent_pubkey_path }}"
        - "{{ amz_cwagent_sig_path }}"
        - "{{ amz_cwagent_pkg_path }}"
      changed_when: no
      ignore_errors: yes
  tags: amz_cwagent
